# Generated by Django 3.2.3 on 2021-05-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_bid_bid_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='number_of_bids',
            field=models.IntegerField(default=0),
        ),
    ]
